config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  post "users", to: "users#create"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username,
  presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
  presence: true,
  uniqueness: { case_sensitive: false },
  length: {  maximum: 105 },
  format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern

  # # Changes to the importmap will invalidate the etag for HTML responses
  # stale_when_importmap_changes
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  def edit
  end
  def create
    @article = Article.new(article_params)
    @article.user = User.first

    if @article.save
      flash[:notice]="Article was successfully created."
      redirect_to @article

    else
      render :new, status: :unprocessable_entity

    end
  end

  def update
    if @article.update(article_params)
        flash[:notice] = "Article was updated successfully"
        redirect_to @article
    else
      render :edit, status: :unprocessable_entity

    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end
  # # GET /articles/1/edit
  # def edit
  # end

  # # POST /articles or /articles.json
  # def create
  #   @article = Article.new(article_params)

  #   respond_to do |format|
  #     if @article.save
  #       format.html { redirect_to @article, notice: "Article was successfully created." }
  #       format.json { render :show, status: :created, location: @article }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /articles/1 or /articles/1.json
  # def update
  #   respond_to do |format|
  #     if @article.update(article_params)
  #       format.html { redirect_to @article, notice: "Article was successfully updated.", status: :see_other }
  #       format.json { render :show, status: :ok, location: @article }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /articles/1 or /articles/1.json
  # def destroy
  #   @article.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to articles_path, notice: "Article was successfully destroyed.", status: :see_other }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_article
  #     @article = Article.find(params.expect(:id))
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def article_params
  #     params.expect(article: [ :title, :description ])
  #   end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @articles = @user.articles
    render "users/show"
  end
  def new
        @user = User.new
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to articles_path
      else
        render "edit"
      end
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = "Welcome to Alpha Blog #{@user.username}"
        redirect_to articles_path

      else
        render "new"
      end
    end

    private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    size = options[:size]
    hash = Digest::MD5.hexdigest(email_address)
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header font-italic">
            by <%= article.user.username if article.user%>
          </div>
          <div class="card-body ">
            <h5 class="card-title">
              <%= link_to article.title, article_path(article) ,class:"text-success"%>
            </h5>
            <p class="card-text">
              <%= truncate(article.description , length:100)%>
            </p>
            <%= link_to "View" , article,class:"btn btn-outline-success "%> 
                

                <%=link_to " Edit ", edit_article_path(article), class:" btn btn-outline-info" %>
              <%= link_to "Delete" , article_path(article) ,data:{turbo_method: :delete,turbo_confirm:"Are you
                sure "}, class:" btn btn-outline-danger" %>
          </div>
        </div>
      </div>
    </div>
    <%end%>
</div>

app/views/articles/_form.html.erb
    <div class="container">


<div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/errors',object: @article  %>
    <%= form_with(model:@article,class:"shadow p-3 mb-3 bg-info rounded",local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :title, class:"col-2 col-form-label text-light"%>
        <div class="col-10">
        <%= f.text_field :title , class:"form-control shadow rounded", placeholder:"Title of article" %>
    </div>
    </div>
<br/>
    <div class="form-group row">

        <%= f.label :description , class: "col-2 col-form-label text-light"%><br/>
        <div class="col-10">
        <%= f.text_area :description,rows:10,class:"form-control shadow rounded" ,placeholder:"Description of article"%>
        </div>
    </div>

    <br/>
    <%# <div class="row justify-content-center"> %>
<div class="mb-3">
        <%= f.submit class:"btn btn-outline-light btn-sm text-light" %>
    <%# </div> %>
    <% end %>
</div>
</div>
</div>
    </div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form'%>

app/views/articles/index.html copy.erb
<%# <p style="color: green"><%= notice %></p> 

<%# <%= content_for :title, "Articles" %> 

 <%# <h1>Articles</h1> %>

<%# <div id="articles"> %>
  <%# <% @articles.each do |article| %> 
    <%# <%= render article %> 
    <%# <p> %>
      <%# <%= link_to "Show this article", article %> 
    <%# </p> %>
  <%# <% end %> 
<%# </div> %>

<%# <%= link_to "New article", new_article_path %> 


  

    <h1 class="text-center mt-4">Listing all articles</h1>

    <%= render 'article'%>

      

app/views/articles/new.html.erb
<%# <% content_for :title, "New article" %>

<%# <h1>New article</h1> %>

<%# <%= render "form", article: @article %> 

<%#<br> %>

<%#<div> %>
<%# <%= link_to "Back to articles", articles_path %>
<%# </div> %>



<h1 class="text-center mt-4">Create a new article</h1>


<%= render 'form'%>

app/views/articles/show.html.erb
<!--
<%# <p style="color: green"><%= notice %></p> %>

<%# <%= render @article %> %>

<%# 
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div> %>

-->





    <h2 class="text-center mt-4"><%= @article.title %></h2>
      <div class="container">
   
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-body rounded">
              <div class="card-header font-italic">
                by <%= @article.user.username %>
              </div>
              <div class="card-body " >
             
                <div class="card-text text-left"><%=simple_format( @article.description )%></div>
              

                <%=link_to "Edit ", edit_article_path(@article), class:"btn btn-outline-info" %>
                <%= link_to "Delete" , article_path(@article) ,data:{turbo_method: :delete,turbo_confirm:"Are you sure "}, class:"btn btn-outline-danger"  %>
              </div>
              </div>
    </div>
    </div>
 
    </div>

      

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Sheral Waskar","https://sheral18.github.io/Portfolio/" , class:"text-white"%></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
    <div class="container">
    <% flash.each do |name,msg| %>
     <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                
            </button>
      </div>
    <%end%>
    </div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg bg-body-tertiary" id="nav">
        <div class="container-fluid">

            <%=link_to "Alpha Blog" , root_path, class:"navbar-brand",id:"logo"%>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
                <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Articles
                </a>
                <ul class="dropdown-menu">
                    <%= link_to "Create new article",new_article_path,class:"dropdown-item"%>
                    <%= link_to "View articles" ,articles_path, class:"dropdown-item"%>
            
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
                </li>
                <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Alpha Blog">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    

    

    
  </head>

  <body class="d-flex flex-column min-vh-500">
  








    <%= render 'layouts/navigation'%>

    <div id="page-content">
    <%= render 'layouts/messages'%>
    <%= yield %>
</div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js" integrity="sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y" crossorigin="anonymous"></script>
  <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1> Welcome to the About Page </h1>

<%= link_to 'Articles listing' , articles_path%>

<%= link_to 'Home Page',root_path%>

app/views/pages/home.html.erb
<div class="container-fluid p-0" >

<div id="photo" class="jumbotron text-center" >
<h1 class="display-4">  Alpha Blog </h1>

<p class="lead">This is a simple hero unit , simple code</p>
<hr class="my-4">
<p>It uses utility classes for typography</p>
<%=link_to "Sign Up!",signup_path , class:"btn btn-success btn-lg" %>

</div>

</div>

app/views/shared/_errors.html.erb
            <% if object.errors.any? %>

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">The following erros prevented the <%=object.class.name.downcase %> from being saved</h4>
            
        

            <ul>
            <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %> </li>
            <% end %>
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                
            </button>
            </div>
            <% end %>

app/views/users/_form.html.erb
    <div class="container">


<div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/errors', object: @user %>
    <%= form_with(model:@user,class:"shadow p-3 mb-3 bg-info rounded",local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :username, class:"col-2 col-form-label text-light"%>
        <div class="col-10">
        <%= f.text_field :username , class:"form-control shadow rounded", placeholder:"Enter a username" %>
    </div>
    </div>
<br/>
    <div class="form-group row">

        <%= f.label :email , class: "col-2 col-form-label text-light"%><br/>
        <div class="col-10">
        <%= f.email_field :email,class:"form-control shadow rounded" ,placeholder:"Enter email id"%>
        </div>
    </div>

    <br/>

        <div class="form-group row">

        <%= f.label :password , class: "col-2 col-form-label text-light"%><br/>
        <div class="col-10">
        <%= f.password_field :password,class:"form-control shadow rounded" ,placeholder:"Choose a password"%>
        </div>
    </div>

    <br/>

    <%# <div class="row justify-content-center"> %>
<div class="mb-3">
        <%= f.submit (@user.new_record? ? "Sign Up" : "Update Account") ,class:"btn btn-outline-light btn-sm text-light"  %>
    <%# </div> %>
    <% end %>
</div>
</div>
</div>
    </div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>


<%= render 'form'%>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>


<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>


<%= gravatar_for @user, size:200  %>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article'%>